[package]
name = "bitcoinbook"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = "0.29.2"
bitcoincore-rpc = "0.16.0"
primitive-types = "0.1.0"
